### PR TITLE
[bugfix] Correct the  content shown in status-bar

### LINKED ISSUE #112: Wrong user name shown in the status bar
When activate the extension, sometimes, in the status bar, it will show: `LeetCode: Host`, which should be `LeetCode: <user name>`

### PR DESCRIPTION
**Pull request by jdneo**
Resolve #112

### CODE REVIEW

File: src/leetCodeManager.ts [hunk 1]
```diff
@@ -117,6 +117,19 @@ class LeetCodeManager extends EventEmitter {
     public getUser(): string | undefined {
         return this.currentUser;
     }
+
+    private tryParseUserName(output: string): string {
+        const lines: string[] = output.trim().split(/\r?\n/);
+        if (lines.length === 3) {
+            const reg: RegExp = /^\s*.{1}\s*(.+)\s*https:\/\/leetcode/;
```
Comment (Vigilans) [inline src/leetCodeManager.ts]: The regex executing on 
```
'    ×      vigilans             https://leetcode-cn.com'
```
will return
```
'vigilans             '
```
Append `?` to `.+` to prevent greedy match could solve the problem.

Besides, is there any difference between `.{1}` and `.`?

Comment (jdneo) [reply src/leetCodeManager.ts]: Updated
